@HostAddress = https://localhost:17002



POST {{HostAddress}}/chat-agent
Accept: application/json
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
        "content": "Hello, how can I use the ApiService?"
    }
  ]
}

