<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Nats" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <PackageReference Include="SqlSugarCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Perigon\Perigon.AspNetCore\Perigon.AspNetCore.csproj" />
  </ItemGroup>

</Project>
