<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Nullable>enable</Nullable>
        <NoWarn>1701;1702;1591</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\Definition\Share\Share.csproj" />
        <ProjectReference Include="..\..\Perigon\Perigon.AspNetCore.Toolkit\Perigon.AspNetCore.Toolkit.csproj" />
        <ProjectReference Include="..\CoreMod\CoreMod.csproj" />
        <ProjectReference Include="..\SystemMod\SystemMod.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="HtmlAgilityPack" />
        <PackageReference Include="Kreuzberg" />
        <PackageReference Include="Markdig" />
        <PackageReference Include="DocumentFormat.OpenXml" />
        <PackageReference Include="NATS.Client.Core" />
        <PackageReference Include="NATS.Client.JetStream" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="Tesseract" />
        <PackageReference Include="UglyToad.PdfPig" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Managers\" />
        <Folder Include="Models\" />
    </ItemGroup>
</Project>